### ISSUE TITLE
Complete synthetic experiment table outline:

### ISSUE THREAD

**Issue by mhrmm** [Mark-Hopkins-at-Reed/thesis-jillian-james#16]
- which parameters will you explore:
   - num gen pretrain = { ... }?
   - num disc pretrain = 
   - num adversarial =
   - num eaters/foods = 
   - num training data = .

**Comment by jiljames** [comment]
Hi Mark, for this would you like me to create a shell script with all the commands for the experiments I'm running or something? Or are you just wanting me to list what parameters I'm changing and their inputs in like a text file?

**Comment by mhrmm** [comment]
Either would be fine for now, I think.
