### ISSUE TITLE
Automate experiment pipeline.

### ISSUE THREAD

**Issue by mhrmm** [Mark-Hopkins-at-Reed/thesis-jillian-james#18]

**Comment by jiljames** [comment]
Hi Mark. I remember you said during our thesis meeting that it might be a good idea to move the synthetic data generation into gan.py. So are you wanting me to just move all the functions in synthetic.py into gan.py?

**Comment by jiljames** [comment]
Nevermind I went about doing it in what I think might be a neater way. : )

**Comment by mhrmm** [comment]
Sounds good!
