### ISSUE TITLE
week by week plan for thesis

### ISSUE THREAD

**Issue by mhrmm** [Mark-Hopkins-at-Reed/thesis-jillian-james#23]
https://docs.google.com/spreadsheets/d/1uWpTONhT5Q6-SkRjIAvQXcGDGilgQSKOCFekU-geRaM/edit?usp=sharing

**Comment by jiljames** [comment]
https://docs.google.com/spreadsheets/d/1eyoILn5Lup8KEo-4Qqu5DJtg-6sWdwo7lKDLiietAZc/edit?usp=sharing

The other document was only in view mode so I pasted it in this one which is shared with you
